name: Generate Lunar Calendar

on:
  schedule:
    - cron: '0 0 1 1 *' # 每年1月1日运行
  workflow_dispatch: # 手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -i https://pypi.tuna.tsinghua.edu.cn/simple chinese-calendar ics

      - name: Generate calendar
        run: python generate_calendar.py

      - name: Upload calendar
        uses: https://ghproxy.com/https://github.com/actions/upload-artifact@v3.1.2
        with:
          name: lunar_calendar
          path: lunar_calendar.ics
